language: node_js
sudo: false

node_js:
  - "8"
  - "9"

cache:
  yarn: true
  directories:
    - "node_modules"

script:
  - yarn run lint
  - yarn run coverage
  - yarn run build

after_success:
  - yarn add codecov && ./node_modules/.bin/codecov
